export const siteConfig = {
    name: "Ahmad Fadlih Wahyu Sardana",
    title: "Ahmad Fadlih Wahyu Sardana | Fullstack Developer building AI automation products",
    description:
        "Portfolio of Ahmad Fadlih Wahyu Sardana, a D4 Informatics Engineering student focused on fullstack development, AI automation workflows, decision systems, and realtime dashboards.",
    url: "https://ahmad-fadlih-portfolio.vercel.app",
    ogImage: "/og-image.png",
    author: "Ahmad Fadlih Wahyu Sardana",
    username: "afadlih",
    keywords: [
        "Ahmad Fadlih",
        "Ahmad Fadlih Wahyu Sardana",
        "afadlih",
        "Fullstack Developer",
        "AI Automation Products",
        "AI Product Engineering",
        "AI Workflow Apps",
        "Google Form Automation",
        "Decision System",
        "Realtime IoT Dashboard",
        "Next.js",
        "React",
        "TypeScript",
        "Tailwind CSS",
        "Python",
        "FastAPI",
        "Gemini API",
        "Firebase",
        "MQTT",
        "Docker",
        "GitHub Actions",
        "Portfolio",
    ],
};
